
GET http://localhost:5000/api/auth/

###

GET http://localhost:5000/api/auth/users

###

POST http://localhost:5000/auth/register
Content-Type: application/json

{
  "username": "hoanpd",
  "password": "admin"
}

###

POST http://localhost:5000/auth/login
Content-Type: application/json

{
  "username": "hoanpd",
  "password": "admin"
}

###
POST http://localhost:5000/auth/resetUUID
Content-Type: application/json

{
  "username": "DiemLinhCo"
}