
GET http://localhost:5000/api/auth/

###

GET http://localhost:5000/api/auth/users

###

POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "username": "DiemLinhCo",
  "password": "DLC"
}

###

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "username": "DiemLinhCo",
  "password": "DLC"
}